idf_component_register(
    SRCS
        alarm_audio.c
        alarm_logic.c
        app_settings.c
        clock_ui.c
        clock_model.c
        main.c
        app_controller.c
        wifi_time.c
        assets/alarm_pcm.c
        assets/slava_face_img.c
        assets/slava_dark_face_img.c
    INCLUDE_DIRS .)
