idf_component_register(
    SRCS
        alarm_audio.c
        alarm_logic.c
        app_settings.c
        clock_ui.c
        clock_model.c
        main.c
        app_controller.c
        wifi_time.c
        assets/alarm_pcm.c
        assets/dseg7_classic_italic_112.c
        assets/dseg7_classic_italic_56.c
        assets/dseg14_classic_italic_36.c
        assets/dseg14_classic_italic_24.c
        assets/dseg14_classic_italic_20.c
        assets/slava_face_img.c
        assets/slava_dark_face_img.c
        ui/ui_controls.c
        ui/ui_surface.c
    INCLUDE_DIRS .)
